apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: wasm
spec:
  type: middleware.http.wasm.basic
  version: v1
  metadata:
  - name: path
    value: "C:/_dev/azure.samples/aks_wasm_dotnet/dotnet_dapr/bin/Debug/net7.0/dotnet_dapr.wasm"
  - name: runtime
    value: "wazero"