apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ai-service-scaler
spec:
  scaleTargetRef:
    name: ai-service
  pollingInterval: 5
  cooldownPeriod: 30
  minReplicaCount: 1
  maxReplicaCount: 2
  triggers:
    - type: cpu
      metadata:
        value: "8"
        type: "Utilization"
