kind: Installation
apiVersion: operator.tigera.io/v1
metadata:
  name: default
spec:
  kubernetesProvider: AKS
  cni:
    type: Calico
  calicoNetwork:
    bgp: Disabled
    ipPools:
    - cidr: 192.168.0.0/24
      encapsulation: VXLAN #VXLANCrossSubnet

---

apiVersion: operator.tigera.io/v1
kind: APIServer
metadata:
  name: default
spec: {}