openapi: 3.0.1
info:
  title: versionedapi
  description: ""
  version: ""
servers:
  - url: https://www.bing.com
paths:
  /:
    get:
      summary: GET
      description: GET
      operationId: get
      responses:
        "200":
          description: ""
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: []
  - apiKeyQuery: []
