apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: prometheus-scaledobject
  namespace: ingress-nginx
spec:
  scaleTargetRef:
      name: function-helloworld-http
  pollingInterval: 15
  cooldownPeriod:  30
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
      metricName: nginx_service_requests_total
      threshold: '1'
      query: sum(rate(nginx_ingress_controller_nginx_process_connections_total[1m]))