name: Container image scanning and certification

on:
  workflow_dispatch:
    inputs:
      image:
        description: "Image to scan and certify"
        required: true
        default: "mcr.microsoft.com/azure-api-management/gateway:2.8.0"
        type: string
      severity:
        description: "Severities that will be considered as failures"
        required: true
        default: "CRITICAL,HIGH"
        type: string

permissions: read-all

jobs:
  check-image:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: " ${{ github.event.inputs.image }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "${{ github.event.inputs.severity }}"
